### ISSUE TITLE
Maps/Data: Popup-Inhalt wird als HTML angezeigt

### ISSUE THREAD

**Issue by TynaE** [Kuestenschmiede/DataBundle#11]
Nach einem Update von Contao 4.9 auf 4.13 werden die Inhalte im Karten-Popup als HTML-Code angezeigt.

Die Marker für die Karte werden über con4gis/data erfasst.
Wenn ein Marker direkt in der Kartenstruktur als „Einzelne Geo-Koordinate“ anlegt wird, dann wird der Popup-Inhalt richtig ausgegeben.

Contao 4.13.43
con4gis maps 8.2.25
con4gis data 1.3.5

**Comment by coastforge-mei** [comment]
Behoben in 1.3.6. Danke für die Meldung.
